services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: valkey/valkey:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
    env_file: server/.env
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
      CHAT_RS_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
      CHAT_RS_REDIS_URL: redis://redis:6379
      CHAT_RS_SECRET_KEY: NWk8wRQsR3r20r1KsAkzi/akBJ1TeZDBT9gB26DnSRsI

volumes:
  postgres_data:
  redis_data:
