services:
  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: valkey/valkey:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  streamer:
    image: tinistreamer-streamer
    container_name: tinistream
    ports:
      - "8081:8081"
    environment:
      STREAMER_PORT: 8081
      STREAMER_SERVER_ADDRESS: http://localhost:8081
      STREAMER_REDIS_URL: redis://redis:6379
      STREAMER_TTL: 120
    env_file: server/.env
    depends_on:
      - redis

  rschat:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
      RS_CHAT_SERVER_ADDRESS: http://localhost:8080
      RS_CHAT_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
      RS_CHAT_REDIS_URL: redis://redis:6379
      RS_CHAT_DATA_DIR: /data
    env_file: server/.env
    volumes:
      - ./.docker:/certs
      - rschat_data:/data
    depends_on:
      - db
      - redis
      - streamer

volumes:
  postgres_data:
  redis_data:
  rschat_data:
