[package]
name = "chat-rs-api"
version = "0.1.0"
edition = "2021"
publish = false

[profile.release]
opt-level = 2
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
diesel = { version = "2.2.10", features = ["postgres", "chrono", "uuid"] }
diesel-async = { version = "0.5.2", features = ["deadpool", "postgres"] }
diesel_async_migrations = "0.15.0"
dotenvy = "0.15.7"
rocket = { version = "0.5.1", features = ["json"] }
rocket_okapi = { version = "0.9.0", features = ["rapidoc"] }
schemars = { version = "0.8.22", features = ["chrono"] }
serde = { version = "1.0.219" }
serde_json = "1.0.140"
tokio = { version = "1.45.1" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
