/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as AppAppLayoutRouteImport } from './routes/app/_appLayout'
import { Route as AppAppLayoutIndexRouteImport } from './routes/app/_appLayout/index'
import { Route as AppAppLayoutProfileRouteImport } from './routes/app/_appLayout/profile'
import { Route as AppAppLayoutAppKeysRouteImport } from './routes/app/_appLayout/app-keys'
import { Route as AppAppLayoutApiKeysRouteImport } from './routes/app/_appLayout/api-keys'
import { Route as AppAppLayoutSessionSessionIdRouteImport } from './routes/app/_appLayout/session/$sessionId'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppLayoutRoute = AppAppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => AppRoute,
} as any)
const AppAppLayoutIndexRoute = AppAppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutProfileRoute = AppAppLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutAppKeysRoute = AppAppLayoutAppKeysRouteImport.update({
  id: '/app-keys',
  path: '/app-keys',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutApiKeysRoute = AppAppLayoutApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppAppLayoutRoute,
} as any)
const AppAppLayoutSessionSessionIdRoute =
  AppAppLayoutSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AppAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppLayoutRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/api-keys': typeof AppAppLayoutApiKeysRoute
  '/app/app-keys': typeof AppAppLayoutAppKeysRoute
  '/app/profile': typeof AppAppLayoutProfileRoute
  '/app/': typeof AppAppLayoutIndexRoute
  '/app/session/$sessionId': typeof AppAppLayoutSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAppLayoutIndexRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/api-keys': typeof AppAppLayoutApiKeysRoute
  '/app/app-keys': typeof AppAppLayoutAppKeysRoute
  '/app/profile': typeof AppAppLayoutProfileRoute
  '/app/session/$sessionId': typeof AppAppLayoutSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/_appLayout': typeof AppAppLayoutRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/_appLayout/api-keys': typeof AppAppLayoutApiKeysRoute
  '/app/_appLayout/app-keys': typeof AppAppLayoutAppKeysRoute
  '/app/_appLayout/profile': typeof AppAppLayoutProfileRoute
  '/app/_appLayout/': typeof AppAppLayoutIndexRoute
  '/app/_appLayout/session/$sessionId': typeof AppAppLayoutSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/api-keys'
    | '/app/app-keys'
    | '/app/profile'
    | '/app/'
    | '/app/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/api-keys'
    | '/app/app-keys'
    | '/app/profile'
    | '/app/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/_appLayout'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/_appLayout/api-keys'
    | '/app/_appLayout/app-keys'
    | '/app/_appLayout/profile'
    | '/app/_appLayout/'
    | '/app/_appLayout/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_appLayout': {
      id: '/app/_appLayout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_appLayout/': {
      id: '/app/_appLayout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppLayoutIndexRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/profile': {
      id: '/app/_appLayout/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppLayoutProfileRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/app-keys': {
      id: '/app/_appLayout/app-keys'
      path: '/app-keys'
      fullPath: '/app/app-keys'
      preLoaderRoute: typeof AppAppLayoutAppKeysRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/api-keys': {
      id: '/app/_appLayout/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppAppLayoutApiKeysRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
    '/app/_appLayout/session/$sessionId': {
      id: '/app/_appLayout/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/app/session/$sessionId'
      preLoaderRoute: typeof AppAppLayoutSessionSessionIdRouteImport
      parentRoute: typeof AppAppLayoutRoute
    }
  }
}

interface AppAppLayoutRouteChildren {
  AppAppLayoutApiKeysRoute: typeof AppAppLayoutApiKeysRoute
  AppAppLayoutAppKeysRoute: typeof AppAppLayoutAppKeysRoute
  AppAppLayoutProfileRoute: typeof AppAppLayoutProfileRoute
  AppAppLayoutIndexRoute: typeof AppAppLayoutIndexRoute
  AppAppLayoutSessionSessionIdRoute: typeof AppAppLayoutSessionSessionIdRoute
}

const AppAppLayoutRouteChildren: AppAppLayoutRouteChildren = {
  AppAppLayoutApiKeysRoute: AppAppLayoutApiKeysRoute,
  AppAppLayoutAppKeysRoute: AppAppLayoutAppKeysRoute,
  AppAppLayoutProfileRoute: AppAppLayoutProfileRoute,
  AppAppLayoutIndexRoute: AppAppLayoutIndexRoute,
  AppAppLayoutSessionSessionIdRoute: AppAppLayoutSessionSessionIdRoute,
}

const AppAppLayoutRouteWithChildren = AppAppLayoutRoute._addFileChildren(
  AppAppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAppLayoutRoute: typeof AppAppLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppLayoutRoute: AppAppLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
