[package]
name = "rs-chat-api"
version = "0.1.0"
edition = "2024"
description = "RsChat Server"
publish = false

[dependencies]
aes-gcm = "0.11.0"
aide = {
  git = "https://github.com/hniksic/aide.git",
  rev = "7246c20",
  features = ["axum", "axum-json", "axum-query", "macros", "swagger"]
}
anyhow = "1.0.103"
async-stream = "0.3.6"
async-trait = "0.1.89"
axum = { version = "0.8.9", features = ["json", "multipart", "query"] }
axum-aide-macros = {
  git = "https://git.fasharp.io/fa-sharp/axum-aide-macros",
  rev = "5b00e645df"
}
axum-helmet = "1.0.2"
axum-plugin = {
  git = "https://git.fasharp.io/fa-sharp/axum-plugin",
  rev = "be17dc9aec",
  features = ["figment"]
}
bigdecimal = { version = "0.4.10", features = ["serde-json"] }
chrono = {
  version = "0.4.45",
  default-features = false,
  features = ["now", "serde", "std"]
}
diesel = {
  version = "2.3.11",
  default-features = false,
  features = ["chrono", "numeric", "serde_json", "uuid"]
}
diesel-async = {
  version = "0.9.2",
  features = ["deadpool", "migrations", "postgres"]
}
diesel-derive-enum = { version = "3.0.0-beta.1", features = ["postgres"] }
diesel-jsonb-derive = { path = "crates/diesel-jsonb-derive" }
diesel_migrations = { version = "2.3.2", features = ["postgres"] }
dotenvy = "0.15.7"
fred = {
  version = "10.1.0",
  default-features = false,
  features = ["i-keys", "i-streams"]
}
futures = "0.3.32"
hex = "0.4.3"
reqwest = {
  version = "0.13.4",
  default-features = false,
  features = ["default-tls", "json", "stream"]
}
reqwest-websocket = { version = "0.6.0", features = ["json"] }
schemars = {
  version = "1.2.1",
  features = ["bigdecimal04", "chrono04", "preserve_order", "uuid1"]
}
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_with = {
  version = "3.21.0",
  default-features = false,
  features = ["macros"]
}
simple-oauth = { version = "0.1.0-beta.1", features = ["default-tls"] }
strum = {
  version = "0.28.0",
  default-features = false,
  features = ["derive", "std"]
}
thiserror = "2.0.18"
tinistream-client = {
  git = "https://github.com/fa-sharp/tinistream",
  rev = "015d307"
}
tokio = {
  version = "1.52.3",
  default-features = false,
  features = ["macros", "net", "rt", "rt-multi-thread", "signal"]
}
tokio-stream = { version = "0.1.18", default-features = false }
tokio-util = { version = "0.7.18", features = ["io"] }
tower = { version = "0.5", default-features = false }
tower-http = {
  version = "0.7.0",
  features = ["fs", "limit", "request-id", "timeout", "trace"]
}
tower-sessions = {
  version = "0.15.0",
  default-features = false,
  features = ["axum-core", "memory-store", "private"]
}
tower-sessions-redis-store = {
  git = "https://github.com/maxcountryman/tower-sessions-stores",
  rev = "69e025f"
}
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
uuid = { version = "1.23.5", features = ["serde", "v4"] }
