name: CI
on:
  push:
    branches: ["main"]
    tags-ignore: ["v*"]
    paths:
      - "server/**"
      - "server-new/**"
      - "web/**"
      - Dockerfile
  pull_request:
    types: [opened, synchronize, reopened]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RUST_VERSION: "1.96"
  NODE_VERSION: 22

jobs:
  build-web:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          package_json_file: web/package.json
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: web/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint:ci
      - name: Check types
        run: pnpm typecheck
      - name: Build
        run: pnpm build

  build-server:
    name: Build server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-new
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        run: rustup toolchain install ${{ env.RUST_VERSION }} --profile minimal --no-self-update && rustup default ${{ env.RUST_VERSION }}
      - name: Setup rust-cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./server-new

      - name: Run cargo check
        run: cargo check

      - name: Run cargo build
        run: cargo build

      # - name: Test crate
      #   run: cargo nextest run --all-features --profile ci
      # - name: Test docs
      #   run: cargo test --doc --all-features
